services:
    app:
        container_name: app
        networks:
            - laravel000net1
        build: ./docker/php
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./log:/var/log
        depends_on:
            - db

    web:
        container_name: nginx
        networks:
            - laravel000net1
        image: nginx
        ports:
            - "28021:28021"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db

    db:
        image: mysql:latest
        networks:
            - laravel000net1
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - "28022:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-dl2
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - db
        ports:
            - 8580:80
        volumes:
            - /sessions

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080

networks:
    laravel000net1:
